{% set name = "docker-map" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c4d6282e5e1d2a7d9ace9030ada7caf5a9576111388ed04013a67d7656030aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - six
  run:
    - python
    - six
    - docker-py

test:
  imports:
    - dockermap
    - dockermap.build
    - dockermap.client
    - dockermap.map
    - dockermap.map.action
    - dockermap.map.config
    - dockermap.map.policy
    - dockermap.map.runner
    - dockermap.map.state
    - dockermap.map.state.update
    - tests

about:
  home: https://github.com/merll/docker-map
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Managing Docker images, containers, and their dependencies in Python.

extra:
  recipe-maintainers:
    - kszucs
