travis:
  secure:
    BINSTAR_TOKEN: bPOf4xtIVCAggbspqNKi/wZtlL2po4ACqhRseHpIynJxanYP41rdhZGNWCqQrm3LhMU57sp7HEyy4DxHlDF5wUSRDV8pV8DloMVxLoOSw6n6j9i3Z0/8nM1rVboa14H1xiP1502sXRXBf4TKBNn+KxbJ4tICspPHkAgjjxhrupgPc6+IwkwZCFjclLouSRCbKFwT8qJHlDgdleeUxY6+fdLqPflrgS7izkfOKoZH00wH7UX7HapcaSW2bF5IO/eFYQ/BIqzJ9Qv1wOEjRvRZoNW1EvQpzC5VElqlnC2p0+npi60aS1UqywHHffzpgJQYmkM32V4Lgn77UH2HJJG9d5pTX3ubZawK6TrA/8Q1gPk+ZU8k2FSpvpGCam1UxI4AIgG53lXu1TBubfqVeIt8J58NuAMRb0z5V/auMX6i0Ze/JDRbNglIfhO14UfXbZSCJKQQ/lMHpIT+PNFmHcb4QYPe1VG5WfRC8lDdg1V7qpdLu2mAao2BNtEP9+bJdw6DsVgKPq7WMUOHblcQVC29/m777LftFAnj4FiUJrbLwjudM9DAlSQYssBkqqN3QcWC4GjmLhi9hCCAoBqa+fymwfeHnoGJHUjPTWrCU4aoMNHFAuNObFRs0GF2QGXg94Mu1iqn7BsvjL3j0p4CFBtdgh5LzxxhiEMOIDBxRHfszMY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
